CREATE TABLE board (
    id                  UUID NOT NULL,
    name                VARCHAR(50) NOT NULL,
    description         VARCHAR(300) NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE,

    CONSTRAINT pk_board PRIMARY KEY (id)
);

CREATE TABLE category (
    id                  UUID NOT NULL,
    board_id            UUID NOT NULL,
    name                VARCHAR(255) NOT NULL,
    description         VARCHAR(255) NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE,

    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT fk_category_board FOREIGN KEY (board_id) REFERENCES board (id)
);

CREATE INDEX idx_category_board_id ON category (board_id);

CREATE TABLE post (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    board_id            UUID NOT NULL,
    category_id         UUID NOT NULL,
    title               VARCHAR(255),
    content             VARCHAR(5000),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE,
    deleted             BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP WITH TIME ZONE,
    author_user_id      UUID NOT NULL,

    CONSTRAINT pk_post PRIMARY KEY (id),
    CONSTRAINT fk_post_board FOREIGN KEY (board_id) REFERENCES board (id),
    CONSTRAINT fk_post_category FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE INDEX idx_post_board_created_id ON post (board_id, created_at DESC, id DESC);
CREATE INDEX idx_post_category_created_id ON post (category_id, created_at DESC, id DESC);

CREATE TABLE user_snapshot (
    user_id             UUID NOT NULL,
    display_name        VARCHAR(255) NOT NULL,
    last_updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_user_snapshot PRIMARY KEY (user_id)
);

CREATE TABLE comment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id             BIGINT NOT NULL,
    parent_id           BIGINT,
    content             VARCHAR(255) NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted             BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMP WITH TIME ZONE,
    author_user_id      UUID NOT NULL,

    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES post (id),
    CONSTRAINT fk_comment_parent FOREIGN KEY (parent_id) REFERENCES comment (id),
    CONSTRAINT fk_comment_author FOREIGN KEY (author_user_id) REFERENCES user_snapshot (user_id)
);

CREATE INDEX idx_comment_post_created_id ON comment (post_id, created_at, id);
CREATE INDEX idx_comment_parent_id ON comment (parent_id);

CREATE TABLE post_reaction (
    id                  UUID NOT NULL,
    post_id             BIGINT NOT NULL,
    user_id             UUID NOT NULL,
    reaction_type       VARCHAR(255) NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_post_reaction PRIMARY KEY (id),
    CONSTRAINT uk_post_id_user_id_reaction_type UNIQUE (post_id, user_id, reaction_type),
    CONSTRAINT fk_post_reaction_post FOREIGN KEY (post_id) REFERENCES post (id),
    CONSTRAINT fk_post_reaction_user FOREIGN KEY (user_id) REFERENCES user_snapshot (user_id)
);

CREATE INDEX idx_post_reaction_user_created ON post_reaction (user_id, created_at DESC, post_id DESC);

CREATE TABLE post_view (
    post_id             BIGINT NOT NULL,
    count               BIGINT NOT NULL,
    last_viewed_at      TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT pk_post_view PRIMARY KEY (post_id),
    CONSTRAINT fk_post_view_post FOREIGN KEY (post_id) REFERENCES post (id)
);
